In [2]:
from pathlib import Path
import sys

import psycopg2
from psycopg2 import sql
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

from db import get_db_config, fetch_table_df, get_db

In [3]:
conn = get_db()
cur = conn.cursor()

In [4]:
# cur.execute("""commit;""")
# cur.fetchall()

In [20]:
# # delete all data from all tables and reset auto-incrementing ids
# cur.execute("""
# TRUNCATE TABLE 
# questions,
# users,
# subjects,
# topics,
# questions,
# reviews,
# badges,
# stats,
# settings,
# user_subjects,
# user_badges,
# sync_meta
# RESTART IDENTITY CASCADE;
# """)
# cur.execute("""commit;""")

In [5]:
# # delete all data from all tables and reset auto-incrementing ids
# cur.execute("""
# TRUNCATE TABLE 
# questions,
# users,
# subjects,
# topics,
# questions,
# reviews,
# badges,
# stats,
# settings,
# user_subjects,
# user_badges,
# sync_meta
# RESTART IDENTITY CASCADE;
# """)
# cur.execute("""commit;""")

In [6]:
# # schema info
# cur.execute("""
# SELECT
#     conrelid::regclass AS table_name,
#     conname AS constraint_name,
#     pg_get_constraintdef(oid) AS definition
# FROM pg_constraint
# WHERE contype IN ('p','u')
# ORDER BY table_name;
# """)

# tables = cur.fetchall()
# tables

In [18]:
# Sample excute query
cur.execute("""
SELECT user_id, key, value
FROM settings
WHERE key = 'sync_mode'


""")

tables = cur.fetchall()
tables

[]

In [8]:
# List all tables in the database
cur.execute("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
""")
cur.fetchall()

[('questions',),
 ('user_subjects',),
 ('reviews',),
 ('sync_meta',),
 ('settings',),
 ('badges',),
 ('users',),
 ('stats',),
 ('user_badges',),
 ('topics',),
 ('subjects',)]

In [60]:
fetch_table_df('users', 50)

   id      name                 created_at
0   1     Bhavi 2026-03-16 21:14:26.558551
1   2     Madhu 2026-03-16 21:14:26.558551
2   3  Quiz Kid 2026-03-16 21:14:26.558551

In [61]:
fetch_table_df('subjects', 50)

   id         name
0   1  Mathematics
1   2      English
2   3      Science

In [62]:
# IF parent_topic_id is null, then topic is a subtopic, else it's a main topic
fetch_table_df('topics', 100)

,id,subject_id,parent_topic_id,key,name
0,1,1,NaN,multiplication_tables,Multiplication Tables
1,2,1,1.0,tables_1_5,Tables 1-5
2,3,1,1.0,tables_6_10,Tables 6-10
3,4,1,1.0,tables_11_15,Tables 11-15
4,5,1,1.0,tables_16_20,Tables 16-20
5,6,1,NaN,addition,Addition
6,7,1,NaN,subtraction,Subtraction
7,8,1,NaN,division,Division
8,9,1,NaN,fractions,Fractions
9,10,1,NaN,word_problems,Word Problems
10,11,2,NaN,word_spellings,Word Spellings
11,12,2,11.0,two_letter_words,2 Letter Words
12,13,2,11.0,three_letter_words,3 Letter Words
13,14,2,11.0,four_letter_words,4 Letter Words
14,15,2,11.0,five_letter_words,5 Letter Words
15,16,2,11.0,six_letter_words,6 Letter Words
16,17,2,11.0,seven_letter_words,7 Letter Words
17,18,2,NaN,jumbled_words,Jumbled Words
18,19,2,18.0,jumble_three_letter,3 Letter Jumble
19,20,2,18.0,jumble_five_letter,5 Letter Jumble
20,21,3,NaN,science_spellings,Science Spellings
21,22,3,21.0,science_short_words,Science Short Words
22,23,3,21.0,science_long_words,Science Long Words

In [63]:
fetch_table_df('questions', 50)

,id,topic_id,type,question,answer
0,1,6,math-addition,4 + 3 = ?,7
1,2,6,math-addition,9 + 6 = ?,15
2,3,7,math-subtraction,12 - 5 = ?,7
3,4,7,math-subtraction,18 - 9 = ?,9
4,5,8,math-division,24 / 6 = ?,4
5,6,8,math-division,35 / 5 = ?,7
6,7,9,fractions,What fraction of 8 slices is 4 slices?,1/2
7,8,9,fractions,What fraction of 10 stars is 5 stars?,1/2
8,9,10,word-problem,Ria has 3 apples and gets 4 more. How many app...,7
9,10,10,word-problem,There are 12 birds and 5 fly away. How many ar...,7
10,11,12,spelling-fill-blank,Fill in the blank: I am __ school.,at
11,12,12,spelling-fill-blank,Fill in the blank: We go __ home.,to
12,13,13,spelling-fill-blank,Fill in the blank: The cat sat on the m_t.,mat
13,14,13,spelling-fill-blank,Fill in the blank: The sun is h_t.,hot
14,15,14,spelling-fill-blank,Fill in the blank: The fish can s__m fast.,swim
15,16,14,spelling-fill-blank,Fill in the blank: We read a b__k.,book
16,17,15,spelling-fill-blank,Fill in the blank: I like to r__d books.,read
17,18,15,spelling-fill-blank,Fill in the blank: We plant a s__ed in soil.,seed
18,19,16,spelling-fill-blank,Fill in the blank: The bright p__ple flower sm...,purple
19,20,16,spelling-fill-blank,Fill in the blank: We saw a r__bit in the garden.,rabbit
20,21,17,spelling-fill-blank,Fill in the blank: The r__nbow has many colors.,rainbow
21,22,17,spelling-fill-blank,Fill in the blank: A g__affe has a long neck.,giraffe
22,23,19,jumble-word,Unscramble the word: tac,cat
23,24,19,jumble-word,Unscramble the word: god,dog
24,25,20,jumble-word,Unscramble the word: leapp,apple
25,26,20,jumble-word,Unscramble the word: girte,tiger
26,27,22,science-spelling,Fill in the blank: Plants need a_r.,air
27,28,22,science-spelling,Fill in the blank: The sun gives us h__.,heat
28,29,23,science-spelling,Fill in the blank: A p__net moves around the sun.,planet
29,30,23,science-spelling,Fill in the blank: A r__ket flies into space.,rocket

In [73]:
fetch_table_df('reviews', 30)

,user_id,question_id,repetition,interval,ease_factor,next_review,last_result,rev_id,last_modified_rev,sync_version,updated_at
0,1,1,0,0,2.5,1773675866559,not_started,1,None,1,2026-03-16 21:14:26.558551

In [74]:
fetch_table_df('badges', 50)

Empty DataFrame
Columns: []
Index: []

In [82]:
fetch_table_df('stats', 500)

Empty DataFrame
Columns: []
Index: []

In [81]:
fetch_table_df('settings', 10)

   user_id                         key value          updated_at  sync_version
0        3  selected_subject_id_user_3    60 2026-03-16 21:19:42             1
1        3    selected_topic_id_user_3   NaN 2026-03-16 21:19:42             1

In [77]:
fetch_table_df('user_subjects', 10)

   user_id  subject_id
0        1           1
1        1           2
2        1           3
3        2           1
4        2           2
5        2           3
6        3           1
7        3           2
8        3           3

In [78]:
fetch_table_df('user_badges', 5)

Empty DataFrame
Columns: []
Index: []

In [79]:
fetch_table_df('sync_meta', 5)

Empty DataFrame
Columns: []
Index: []

In [80]:
from tests.check_sync_status import main
main()

========================================
Centralized Sync Status
----------------------------------------
Overall status : unknown
Overall message: None
Overall updated: Never
--------------------
Push status : unknown
Push message: None
Push updated: Never
--------------------
Pull status : unknown
Pull message: None
Pull updated: Never
--------------------
========================================