In [61]:
from pathlib import Path
import sys

import psycopg2
from psycopg2 import sql
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

from db import get_db_config, fetch_table_df, get_db

In [62]:
conn = get_db()
cur = conn.cursor()

In [63]:
# get all tables in db
cur.execute("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
""")
tables = cur.fetchall()
tables

[('reviews',),
 ('questions',),
 ('user_subjects',),
 ('stats',),
 ('badges',),
 ('user_badges',),
 ('settings',),
 ('users',),
 ('subjects',),
 ('topics',)]

In [117]:
fetch_table_df('reviews', 100)

,user_id,question_id,repetition,interval,ease_factor,next_review,last_result,rev_id
0,1,1773384817944,0,0,2.50,1773385432247,again,1773384827454
1,1,1773385272272,1,1,2.50,1773471690367,good,1773385290368
2,3,1773382465142,8,2421,2.66,1982557149482,good,1773382749482
3,3,1773382940682,4,33,2.36,1776234208384,good,1773383008385
4,3,1773383109795,1,1,2.50,1773469515310,good,1773383115336
5,3,1773383216252,1,1,2.50,1773469712222,good,1773383312248
6,3,1773383679931,4,39,2.60,1776753779293,good,1773384179293
7,3,1773384671282,0,0,2.50,1773385297931,again,1773384693131
8,3,1773385236143,0,0,2.50,1773385850545,again,1773385245745
9,3,155,1,1,2.50,1773477624901,good,1773391224933
10,3,210,1,1,2.50,1773484274386,good,1773397874415
11,3,43,1,1,2.50,1773484278779,good,1773397878779
12,1,144,0,0,2.50,1773398540113,again,1773397935336
13,3,183,0,0,2.50,1773400592020,again,1773399987226
14,3,73,1,1,2.50,1773486392642,good,1773399992642
15,3,270,1,1,2.50,1773492095788,good,1773405695851
16,3,1621,1,1,2.50,1773492104594,good,1773405704625
17,1,842,2,6,2.50,1773947985563,good,1773429585600
18,1,851,0,0,2.50,1773430198117,again,1773429593352
19,1,11100,3,15,2.50,1774725602855,good,1773429602887
20,3,12,1,1,2.50,1773571374684,good,1773484974715
21,3,11,1,1,2.50,1773571385511,good,1773484985525
22,3,851,1,1,2.50,1773583775884,good,1773497375910
23,3,11100,1,1,2.50,1773583779293,good,1773497379330
24,3,842,0,0,2.50,1773497988162,again,1773497383407

In [116]:
fetch_table_df('questions', 50)

,id,topic_id,type,question,answer
0,9,9,spelling-fill-blank,Fill in the blank: The cat sat on the m_t.,mat
1,10,9,spelling-fill-blank,Fill in the blank: The sun is h_t.,hot
2,27,13,spelling-fill-blank,Fill in the blank: The fish can s__m fast.,swim
3,28,13,spelling-fill-blank,Fill in the blank: We read a b__k.,book
4,29,14,spelling-fill-blank,Fill in the blank: I like to r__d books.,read
5,30,14,spelling-fill-blank,Fill in the blank: We plant a s__ed in soil.,seed
6,31,15,spelling-fill-blank,Fill in the blank: The bright p__ple flower sm...,purple
7,32,15,spelling-fill-blank,Fill in the blank: We saw a r__bit in the garden.,rabbit
8,33,16,spelling-fill-blank,Fill in the blank: The r__nbow has many colors.,rainbow
9,34,16,spelling-fill-blank,Fill in the blank: A g__affe has a long neck.,giraffe
10,35,21,jumble-word,Unscramble the word: tac,cat
11,36,21,jumble-word,Unscramble the word: god,dog
12,1,4,math-addition,4 + 3 = ?,7
13,2,4,math-addition,9 + 6 = ?,15
14,3,5,math-subtraction,12 - 5 = ?,7
15,4,5,math-subtraction,18 - 9 = ?,9
16,5,6,math-division,24 / 6 = ?,4
17,6,6,math-division,35 / 5 = ?,7
18,19,39,fractions,What fraction of 8 slices is 4 slices?,1/2
19,20,39,fractions,What fraction of 10 stars is 5 stars?,1/2
20,21,40,word-problem,Ria has 3 apples and gets 4 more. How many app...,7
21,22,40,word-problem,There are 12 birds and 5 fly away. How many ar...,7
22,7,8,spelling-fill-blank,Fill in the blank: I am __ school.,at
23,8,8,spelling-fill-blank,Fill in the blank: We go __ home.,to
24,37,22,jumble-word,Unscramble the word: leapp,apple
25,38,22,jumble-word,Unscramble the word: girte,tiger
26,11,12,science-spelling,Fill in the blank: Plants need a_r.,air
27,12,12,science-spelling,Fill in the blank: The sun gives us h__.,heat
28,41,23,science-spelling,Fill in the blank: A p__net moves around the sun.,planet
29,42,23,science-spelling,Fill in the blank: A r__ket flies into space.,rocket

In [115]:
fetch_table_df('user_subjects', 50)

   user_id  subject_id
0        1           1
1        1           2
2        1           3
3        2           1
4        2           2
5        2           3
6        3           1
7        3           2
8        3           3

In [113]:
fetch_table_df('stats', 50)

   id  user_id  correct  wrong            practiced_at
0  33        3        1      0 2026-03-14 19:28:12.626
1  34        3        0      1 2026-03-14 19:28:12.637
2  35        3        1      0 2026-03-14 19:28:12.649
3  36        3        1      0 2026-03-14 19:39:31.368
4  37        3        1      0 2026-03-14 19:39:35.921
5  38        3        1      0 2026-03-14 19:39:39.336
6  39        3        0      1 2026-03-14 19:39:43.416

In [122]:
fetch_table_df('badges', 50)

Empty DataFrame
Columns: []
Index: []

In [121]:
fetch_table_df('user_badges', 5)

Empty DataFrame
Columns: []
Index: []

In [125]:
fetch_table_df('settings', 30)

                           key                              value
0                  active_user                                  1
1   selected_subject_id_user_3                                  1
2     selected_topic_id_user_3                                204
3            theme_mode_user_3                               dark
4             sync_last_status                            success
5            sync_last_message  Last sync completed successfully.
6                 sync_last_at                      1773499631196
7                    sync_mode                              local
8   selected_subject_id_user_1                                  1
9     selected_topic_id_user_1                                204
10           theme_mode_user_1                               dark

In [109]:
from tests.check_sync_status import main
main()

========================================
Centralized Sync Status
----------------------------------------
Status : success
Message: Last sync completed successfully.
Updated: 2026-03-14 19:28:12
========================================