In [2]:
from pathlib import Path
import sys

import psycopg2
from psycopg2 import sql
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

from db import get_db_config, fetch_table_df, get_db

In [3]:
conn = get_db()
cur = conn.cursor()

In [8]:
# get all tables in db
cur.execute("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
""")
tables = cur.fetchall()
tables

[('reviews',),
 ('questions',),
 ('user_subjects',),
 ('stats',),
 ('badges',),
 ('user_badges',),
 ('settings',),
 ('users',),
 ('subjects',),
 ('topics',)]

In [18]:
fetch_table_df('topics', 5)

,id,subject_id,parent_topic_id,key,name
0,1,1,NaN,multiplication_tables,Multiplication Tables
1,2,1,1.0,tables_1_5,Tables 1-5
2,3,1,1.0,tables_6_10,Tables 6-10
3,34,1,1.0,tables_11_15,Tables 11-15
4,35,1,1.0,tables_16_20,Tables 16-20

In [10]:
fetch_table_df('questions', 5)

   id  topic_id              type    question answer
0   1         4     math-addition   4 + 3 = ?      7
1   2         4     math-addition   9 + 6 = ?     15
2   3         5  math-subtraction  12 - 5 = ?      7
3   4         5  math-subtraction  18 - 9 = ?      9
4   5         6     math-division  24 / 6 = ?      4

In [60]:
fetch_table_df('stats', 30)

Empty DataFrame
Columns: []
Index: []

In [ ]:

 ('stats',),

 ('badges',),
 ('user_badges',),
 
 ('settings',),

In [ ]:
from db import execute_query
import pandas as pd
rows = execute_query("""
SELECT id, subject_id, parent_topic_id, key, name
FROM topics
WHERE parent_topic_id = (
  SELECT id FROM topics WHERE key = 'word_spellings'
)
ORDER BY id
""", fetch=True)

pd.DataFrame(rows)

   id  subject_id  parent_topic_id                 key            name
0   8           2                7    two_letter_words  2 Letter Words
1   9           2                7  three_letter_words  3 Letter Words
2  13           2                7   four_letter_words  4 Letter Words
3  14           2                7   five_letter_words  5 Letter Words
4  15           2                7    six_letter_words  6 Letter Words
5  16           2                7  seven_letter_words  7 Letter Words

In [ ]:
execute_query("""


""")

1